services:
  - type: web
    name: foodbook
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: SUPABASE_URL
        value: https://hktbejyuuxxhqtqbneuc.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdGJlanl1dXh4aHF0cWJuZXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTk4NDcsImV4cCI6MjA3MzU3NTg0N30.TJrvlRIpYCY6e4ubVr4UkbQtY-WLM6ATPRkab6rRtN8
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrdGJlanl1dXh4aHF0cWJuZXVjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Nzk5OTg0NywiZXhwIjoyMDczNTc1ODQ3fQ.YzGRrhb2beAhWO8XWKkqkEGNQ4RYC1g3lYTPsKC6NVY
      - key: DATABASE_URL
        value: postgresql://postgres:t9Cbkfyg2PHnzHif@db.hktbejyuuxxhqtqbneuc.supabase.co:5432/postgres
